DROP TABLE IF EXISTS movies;
DROP TABLE IF EXISTS crystals;
DROP TABLE IF EXISTS rivers;
DROP TABLE IF EXISTS songs;
DROP TABLE IF EXISTS teas;
DROP TABLE IF EXISTS ratings;

CREATE TABLE movies (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  director TEXT,
  url TEXT NOT NULL
);
CREATE TABLE crystals (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  url TEXT NOT NULL
);
CREATE TABLE rivers (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  location TEXT,
  description TEXT,
  url TEXT NOT NULL
);
CREATE TABLE songs (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  artist TEXT,
  url TEXT NOT NULL
);
CREATE TABLE teas (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  brand TEXT,
  description TEXT,
  url TEXT NOT NULL
);
CREATE TABLE ratings (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  number INTEGER NOT NULL,
  movie_id BIGINT REFERENCES movies(id)
)
